# Generated by Django 4.2.5 on 2024-07-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
